name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: macOS-15
    timeout-minutes: 10
    strategy:
      matrix:
        xcode:
          - 16.3
    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Run test
        run: |
          xcodebuild test -scheme CurrencyConverter -destination platform="iOS Simulator,name=iPhone 16 Pro"
